name: drawoverotherapps
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  system_alert_window: ^0.3.2+1
  bubble_overlay: ^0.1.2

flutter:
  uses-material-design: true
